spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/auth_db
    username: ${POSTGRES_ADMIN_USER}
    password: ${POSTGRES_ADMIN_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: 8082